- name:    update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name:    restart ssh
  service: name=ssh state=restarted

- name:    restart fail2ban
  service: name=fail2ban state=restarted

- name:    restart ufw
  service: name=ufw state=restarted
  notify:  enable ufw

- name:    enable ufw
  command: ufw --force enable
