- name:    update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name:    restart ssh
  service: name=ssh state=restarted

- name:    restart fail2ban
  service: name=fail2ban state=restarted
