- user:       name=sam comment='Sam Holman' shell=/usr/bin/zsh groups=sudo append=yes generate_ssh_key=yes ssh_key_bits=2048

- name:       Install common packages
  action:     apt pkg={{ item }} state=latest
  with_items:
    - zsh
    - vim
    - git
    - tig
    - tmux
    - silversearcher-ag
    - exuberant-ctags
    - rubygems-integration
    - npm

- name:       Install tmuxinator
  action:     command gem install tmuxinator creates=/usr/local/bin/tmuxinator

- name:       Install jshint
  action:     command npm install -g jshint creates=/usr/local/bin/jshint

- name:       SSHD config
  template:   src=sshd_config dest=/etc/ssh/sshd_config
  notify:     restart ssh

# Dotfile setup
- name:       Clone dotfiles
  git:        repo=https://github.com/samholman/dotfiles.git dest=/home/sam/dotfiles
  sudo:       yes
  sudo_user:  sam

- name:       Dotfile submodules
  command:    git submodule update --init --recursive
  args:
    chdir:    /home/sam/dotfiles
  sudo:       yes
  sudo_user:  sam

- name:       Dotfile setup
  command:    /home/sam/dotfiles/setup.sh -f
  sudo:       yes
  sudo_user:  sam
