- name:       Install php
  action:     apt pkg={{ item }} state=latest
  with_items:
    - php5-cli
    - php5-fpm
    - php5-curl

- name:      Configure PHP
  template:  src=php/fpm/php.ini dest=/etc/php5/fpm/php.ini
  notify: restart php
